USE [DM_JIMDUR]
GO
/****** Object:  Table [dbo].[DIM_CLIENTE]    Script Date: 20/01/2022 20:32:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_CLIENTE](
	[id_cliente] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](200) NOT NULL,
	[departamento] [varchar](50) NOT NULL,
	[provincia] [varchar](50) NOT NULL,
	[distrito] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DIM_CLIENTE] PRIMARY KEY CLUSTERED 
(
	[id_cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_PRODUCTO]    Script Date: 20/01/2022 20:32:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_PRODUCTO](
	[id_producto] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](200) NOT NULL,
	[categoria] [varchar](50) NOT NULL,
 CONSTRAINT [PK_DIM_PRODUCTO] PRIMARY KEY CLUSTERED 
(
	[id_producto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DIM_TIEMPO]    Script Date: 20/01/2022 20:32:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DIM_TIEMPO](
	[id_tiempo] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [date] NOT NULL,
	[dia] [int] NOT NULL,
	[semana] [int] NOT NULL,
	[mes] [int] NOT NULL,
	[anio] [int] NOT NULL,
 CONSTRAINT [PK_DIM_TIEMPO] PRIMARY KEY CLUSTERED 
(
	[id_tiempo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HECHO_VENTA]    Script Date: 20/01/2022 20:32:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HECHO_VENTA](
	[cliente_id] [int] NOT NULL,
	[tiempo_id] [int] NOT NULL,
	[producto_id] [int] NOT NULL,
	[monto_venta] [float] NOT NULL,
	[cantidad_venta] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HECHO_VENTA]  WITH CHECK ADD  CONSTRAINT [FK_HECHO_VENTA_DIM_CLIENTE] FOREIGN KEY([cliente_id])
REFERENCES [dbo].[DIM_CLIENTE] ([id_cliente])
GO
ALTER TABLE [dbo].[HECHO_VENTA] CHECK CONSTRAINT [FK_HECHO_VENTA_DIM_CLIENTE]
GO
ALTER TABLE [dbo].[HECHO_VENTA]  WITH CHECK ADD  CONSTRAINT [FK_HECHO_VENTA_DIM_PRODUCTO] FOREIGN KEY([producto_id])
REFERENCES [dbo].[DIM_PRODUCTO] ([id_producto])
GO
ALTER TABLE [dbo].[HECHO_VENTA] CHECK CONSTRAINT [FK_HECHO_VENTA_DIM_PRODUCTO]
GO
ALTER TABLE [dbo].[HECHO_VENTA]  WITH CHECK ADD  CONSTRAINT [FK_HECHO_VENTA_DIM_TIEMPO] FOREIGN KEY([tiempo_id])
REFERENCES [dbo].[DIM_TIEMPO] ([id_tiempo])
GO
ALTER TABLE [dbo].[HECHO_VENTA] CHECK CONSTRAINT [FK_HECHO_VENTA_DIM_TIEMPO]
GO
